Repository ritikbanger/Hacktoberfest2022-DSA, pull requests merged in 2022-10, with the labels that each got.

#1 Create remove_duplicates.cpp
  29. Codeforces Problems/1532A-ABC.cpp
  29. Codeforces Problems/1629A-DownloadMoreRam.cpp
  29. Codeforces Problems/1629B-GCDArrays.cpp
  29. Codeforces Problems/1631A-MinMaxSwaps.cpp
  29. Codeforces Problems/1631B-Fun_With_Even_Arrays.cpp
  29. Codeforces Problems/1631C-AND_Matching.cpp
  29. Codeforces Problems/1632B-RoofConstruction.cpp
  29. Codeforces Problems/1633B-Minority.cpp
  29. Codeforces Problems/1644A-Div7.cpp
  30. CPP Programs/remove_duplicates.cpp
Labels: HACKTOBERFEST-ACCEPTED

#4 Hacktoberfest2022 Merge_sort.cpp
  06. Sorting/Merge_sort.cpp
Labels: hacktoberfest-accepted

#5 Created code average-of-levels-in-binary-tree.cpp
  14. Tree/average-of-levels-in-binary-tree.cpp
Labels: hacktoberfest-accepted

#3 Add 2 Python Programs
  33. Python Programs/Pokemon-Game.py
  33. Python Programs/Print-IP-Address.py
Labels: hacktoberfest-accepted

#6 Add - Crypto support
  38. Crypto/Activity_Selection_Greedy_algo.c
  38. Crypto/Best time to buy and sell stock(optimized).py
  38. Crypto/Codeforces_Problem_1579E2-38.cpp
  38. Crypto/Defense-of-a-Kingdom.cpp
  38. Crypto/EgyptianFraction.java
  38. Crypto/Fractional Knapsack.py
  38. Crypto/FractionalKnapsack.java
  38. Crypto/Fractional_Knapsack.cpp
  38. Crypto/HuffmanCoding.cpp
  38. Crypto/JobSequencingProblem.java
  38. Crypto/Join_Ropes_Min_Cost.cpp
  38. Crypto/Minimum-platform.cpp
  38. Crypto/MostUnstableArray.cpp
  38. Crypto/N meetings in one room.cpp
  38. Crypto/New-YearPresents.cpp
  38. Crypto/README.md
  38. Crypto/Water_Connection.cpp
  38. Crypto/Weighted_Job _Scheduling.cpp
  38. Crypto/chocolate_distribution.cpp
  38. Crypto/dijkstra.java
  38. Crypto/gasStations.cpp
  38. Crypto/graph colouring using greedy algo.cpp
  38. Crypto/knapsack.cpp
  38. Crypto/kruskals_msp.cpp
  38. Crypto/largest-number-after-mutating-substring.cpp
  38. Crypto/prim's-algorithm.cpp
  38. Crypto/tsp.cpp
  39. Swift/AdjacentPairs.swift
  39. Swift/Chain.swift
  39. Swift/Chunked.swift
  39. Swift/Combinations.swift
  39. Swift/Compacted.swift
  39. Swift/Cycle.swift
  39. Swift/EitherSequence.swift
  39. Swift/FirstNonNil.swift
  39. Swift/FlattenCollection.swift
  39. Swift/Indexed.swift
  39. Swift/Intersperse.swift
  39. Swift/Joined.swift
  39. Swift/MinMax.swift
  39. Swift/Partition.swift
  39. Swift/Permutations.swift
  39. Swift/Product.swift
  39. Swift/RandomSample.swift
  39. Swift/Reductions.swift
  39. Swift/Rotate.swift
  39. Swift/Split.swift
  39. Swift/Stride.swift
  39. Swift/Suffix.swift
  39. Swift/Trim.swift
  39. Swift/Unique.swift
  39. Swift/Windows.swift
Labels: hacktoberfest-accepted

#7 KMP Algorithm in Java Added
  09. String/Kmp_Algorithm.java
  37. Projects/Heart.py
Labels: hacktoberfest-accepted

#9 Solution to Codeforces 1738A GloryAddicts
  29. Codeforces Problems/1738A_GloryAddicts.cpp
Labels: hacktoberfest-accepted

#11 Added Project - Wordle Solver
  37. Projects/Wordle Solver/README.md
  37. Projects/Wordle Solver/scores.csv
  37. Projects/Wordle Solver/sort_words.py
  37. Projects/Wordle Solver/valid_words.txt
  37. Projects/Wordle Solver/wordle_agent.py
  37. Projects/Wordle Solver/words_sorted_on_letter_frequency.txt
Labels: hacktoberfest-accepted

#12 dijkstra.cpp
  dijkstra.cpp
Labels: hacktoberfest-accepted

#17 Java Code to print Pascals Triangle added
  32. Java Programs/PascalsTriangle.java
Labels: hacktoberfest-accepted

#10 eliminate duplicate nodes in linked lis
  30. CPP Programs/eliminateduplicatenodesinlinkedlist.cpp
Labels: hacktoberfest-accepted

#19 Create pattern-N.cpp
  31. Pattern Problems/C++ Patterns/pattern-N.cpp
Labels: hacktoberfest-accepted

#18 Added Infix to Postfix Convertor using stack cpp
  30. CPP Programs/Infix_To_Postfix.cpp
Labels: hacktoberfest-accepted

#8 Find-No-With-even-no-of-digits.java
  04. Arrays/find_number_with_even_no_of_digits.java
Labels: hacktoberfest-accepted

#20 Palindrome-Number.cpp
  27. LeetCode Problems/Palindrome-Number.cpp
Labels: hacktoberfest-accepted

#16 merge sort.c
  36. C Programs/mergesort.c
  36. C Programs/upper_to_lower.c
Labels: hacktoberfest-accepted

#22 Snowflake pattern using turtle in python
  37. Projects/Snowflake.py
Labels: hacktoberfest-accepted

#21 Peak-Index-in-a-Mountain-Array.cpp
  27. LeetCode Problems/Peak-Index-in-a-Mountain-Array.cpp
Labels: hacktoberfest-accepted

#26 Added solution to the rod cutting problem in cpp
  20. Dynamic Programming/rod_cutting.cpp
Labels: hacktoberfest-accepted

#28 Create 1578_Minimum Time to Make Rope Colorful.py
  27. LeetCode Problems/1578_Minimum Time to Make Rope Colorful.py
Labels: hacktoberfest-accepted

#32 26. Remove Duplicates from Sorted Array
  04. Arrays/26_Remove Duplicates from Sorted Array.py
Labels: hacktoberfest-accepted

#33 Ranamed the file as per changes reqd
  15. Binary Search Tree/Binary_Tree_Class_and_BST_inheritance.cpp
Labels: hacktoberfest-accepted

#14 CPP:Leetcode 283:Move Zero to End
  27. LeetCode Problems/move_zeros_to_end.cpp
Labels: hacktoberfest-accepted

#42 Added some Codechef solved problems
  28. Codechef Problems/LUCKYFOUR.cpp
  28. Codechef Problems/PROGLANG.cpp
  28. Codechef Problems/digitsum.cpp
Labels: hacktoberfest-accepted

#48 Create Ford-Fulkerson-Algorithm.c
  18. Greedy/Ford-Fulkerson-Algorithm.c
Labels: hacktoberfest-accepted

#54 Create fiobonacci_no.cpp
  30. CPP Programs/fiobonacci_no.cpp
Labels: hacktoberfest-accepted

#62 Added linkedlist programs in c for hacktoberfest
  36. C Programs/circular_linkedlist.c
  36. C Programs/doubly_linkedlist.c
  36. C Programs/merge_sorted_linkedlist.c
  36. C Programs/single_linkedlist.c
Labels: hacktoberfest-accepted

#63 hacktoberfest-2022
  09. String/Scramble_String.cpp
Labels: hacktoberfest-accepted

#255 Added Codechef Long Challenge October 2022 answers
  28. Codechef Problems/Codechef-October-Long-Challenge-2022/Building_Race.cpp
  28. Codechef Problems/Codechef-October-Long-Challenge-2022/SingleOp1.cpp
  28. Codechef Problems/Codechef-October-Long-Challenge-2022/SingleOp2.cpp
Labels: hacktoberfest-accepted

#44 Create Coinchange.cpp
  30. CPP Programs/Coinchange.cpp
Labels: hacktoberfest-accepted

#40 Leetcode 990 | Satisfiability_of_Equality_Equations.cpp
  27. LeetCode Problems/990_Satisfiability_of_Equality_Equations.cpp
Labels: hacktoberfest-accepted

#134 added code to calculate area and perimeter of circle of given radius in python
  33. Python Programs/areaandperimeterofcircle.py
Labels: hacktoberfest-accepted

#131 SetMatrixZeroes.cpp added
  30. CPP Programs/SetMatrixZeroes.cpp
Labels: hacktoberfest-accepted

#129 Added classical synchronization codes to CPP Programs
  30. CPP Programs/Prod_Consume.cpp
  30. CPP Programs/Reader_writer.c
  30. CPP Programs/Sleeping_Barber.c
Labels: hacktoberfest-accepted

#125 Create nth_tribonacci_number.py
  01. Mathematics/nth_tribonacci_number.py
Labels: hacktoberfest-accepted

#124 added new question of Disjoint Set for hacktober fest 2022
  23. Disjoint Set/Redundant_Connection.cpp
Labels: hacktoberfest-accepted

#141 Added linkedList_Cycle2 Code
  10. Linked List/cpp/linkedList_Cycle2
Labels: hacktoberfest-accepted

#142 Armstrong_Numbers
  36. C Programs/Armstrong_Numbers
Labels: hacktoberfest-accepted

#144 added 2sum in leetcode problems
  27. LeetCode Problems/2sum.cpp
Labels: hacktoberfest-accepted

#146 Create makeChocolate.java
  Codingbat Problems/makeChocolate.java
Labels: hacktoberfest-accepted

#147 Create NAry level order traversal.cpp
  NAry level order traversal.cpp
Labels: hacktoberfest-accepted

#148 Create reverseLinkedList.c
  27. LeetCode Problems/reverseLinkedList.c
Labels: hacktoberfest-accepted

#154 Added a condition for the n queens problem
  19. Backtracking/N-Queens.cpp
  19. Backtracking/N-Queens.exe
Labels: hacktoberfest-accepted

#155 Optimized Boyer moore algorithm
  BoyerMooreAlgorithmInc++
Labels: hacktoberfest-accepted

#157 solved issue #156 spiral matrix
  32. Java Programs/spiralmatrix.java
Labels: hacktoberfest-accepted

#158 Create AnagramStrings.py
  33. Python Programs/AnagramStrings.py
Labels: hacktoberfest-accepted

#371 Palindrome Linked List
  10. Linked List/java/PalindromeLinkedList.java
Labels: hacktoberfest-accepted

#420 Added Binary Search by Pivot Element
  .DS_Store
  05. Searching/BinarySearch_Using_Pivot.cpp
Labels: hacktoberfest-accepted

#418 Binary Search Trees
  17. Graph/BinarySearchTree.cpp
Labels: hacktoberfest-accepted

#417 Create palindromeRecursion
  palindromeRecursion
Labels: hacktoberfest-accepted

#416 Create Prime Number finder
  Prime Number finder
Labels: hacktoberfest-accepted

#430 Calculator using Python
  33. Python Programs/calculator.py
Labels: hacktoberfest-accepted

#427 Added codes of LTIME110 and AUG221
  28. Codechef Problems/AUG221/AandBequal.cpp
  28. Codechef Problems/AUG221/AandBequal.exe
  28. Codechef Problems/AUG221/HELLOEQN.cpp
  28. Codechef Problems/AUG221/HELLOEQN.exe
  28. Codechef Problems/AUG221/MAXSUBS.cpp
  28. Codechef Problems/AUG221/MAXSUBS.exe
  28. Codechef Problems/AUG221/SALESEASON.cpp
  28. Codechef Problems/AUG221/SALESEASON.exe
  28. Codechef Problems/AUG221/TWOTRAINS.cpp
  28. Codechef Problems/AUG221/TWOTRAINS.exe
  28. Codechef Problems/LTIME110/anotherpalindrome.cpp
  28. Codechef Problems/LTIME110/anotherpalindrome.exe
  28. Codechef Problems/LTIME110/ezypronounciation.cpp
  28. Codechef Problems/LTIME110/ezypronounciation.exe
  28. Codechef Problems/LTIME110/intdesign.cpp
  28. Codechef Problems/LTIME110/intdesign.exe
  28. Codechef Problems/LTIME110/largestfamily.cpp
  28. Codechef Problems/LTIME110/largestfamily.exe
  28. Codechef Problems/LTIME110/lastlevels.cpp
  28. Codechef Problems/LTIME110/lastlevels.exe
  28. Codechef Problems/LTIME110/tandf.cpp
  28. Codechef Problems/LTIME110/tandf.exe
  28. Codechef Problems/START51/DiffMedians.cpp
  28. Codechef Problems/START51/DiffMedians.exe
  28. Codechef Problems/START51/Dominantelement.cpp
  28. Codechef Problems/START51/Dominantelement.exe
  28. Codechef Problems/START51/Finalpopulation.cpp
  28. Codechef Problems/START51/Finalpopulation.exe
  28. Codechef Problems/START51/SplitN.cpp
  28. Codechef Problems/START51/SplitN.exe
  28. Codechef Problems/START51/TVdiscount.cpp
  28. Codechef Problems/START51/TVdiscount.exe
Labels: hacktoberfest-accepted

#426 Create HollowDiamond.cpp
  31. Pattern Problems/C++ Patterns/HollowDiamond.cpp
Labels: hacktoberfest-accepted

#423 Added a basic graphic designing code in python
  33. Python Programs/graphic.py
Labels: good first issue

#422 Two Sum
  32. Java Programs/twoSum.java
Labels: hacktoberfest-accepted

#462 binary_search created
  06. Sorting/binary_search.cpp
Labels: hacktoberfest-accepted

#461 Returns the larsgest range from the array given
  33. Python Programs/largest_range.py
Labels: hacktoberfest-accepted

#459 Added Vertex Cover problem
  17. Graph/VertexCoverProblem.cpp
Labels: hacktoberfest-accepted

#458 Created code for lowest common ancestor
  14. Tree/lowestCommonAncestor.java
Labels: hacktoberfest-accepted

#452 Added Java Script Insertion sort
  34. Javascript/InsertionSort.js
Labels: hacktoberfest-accepted

#450 Create palindrome.c
  36. C Programs/palindrome.c
Labels: hacktoberfest-accepted

#448 fabonacii_series.c
  36. C Programs/fabonacii_series.c
Labels: hacktoberfest-accepted

#447 Add files via upload
  03. Recursion/bsrecursion.cpp
  06. Sorting/countingsort.cpp
Labels: hacktoberfest-accepted

#446 Added KMP Code
  40. KMP/KMP.cpp
Labels: hacktoberfest-accepted

#445 Create RodCutting.java
  20. Dynamic Programming/RodCutting.java
Labels: hacktoberfest-accepted

#443 Added Clone_Graph.cpp
  27. LeetCode Problems/Clone_Graph.cpp
Labels: hacktoberfest-accepted

#439 Added recursive files.
  03. Recursion/binrec.c
  03. Recursion/fibrec.c
  03. Recursion/recursive.c
Labels: hacktoberfest-accepted

#438 Create NQueens.cpp
  03. Recursion/NQueens.cpp
Labels: hacktoberfest-accepted

#437 Gokupika patch 1
  04. Arrays/MissingNumber.cpp
  04. Arrays/NextPermutation.cpp
  14. Tree/InorderTraversal.cpp
Labels: hacktoberfest-accepted

#436 calculator.c
  36. C Programs/Calculator.c
Labels: hacktoberfest-accepted

#429 Hacktober
  TwoSum.cpp
Labels: hacktoberfest-accepted

#415 Create NPAIRS.java
  32. Java Programs/NPAIRS.java
Labels: hacktoberfest-accepted

#414 leetcode compliment of base 10 1009
  27. LeetCode Problems/1009-Complement-Of-Base-10-Integer.cpp
Labels: hacktoberfest-accepted

#411 Create Best_time_to_buy_and_sell_stocks_IV.cpp
  27. LeetCode Problems/Best_time_to_buy_and_sell_stocks_IV.cpp
Labels: hacktoberfest-accepted

#410 Added two linked list dsa qs in cpp language
  10. Linked List/q10.cpp
  10. Linked List/q12.cpp
Labels: hacktoberfest-accepted

#409 Added code
  01. Mathematics/Reverse_Integer.cpp
Labels: hacktoberfest-accepted

#406 nauman
  34. Javascript/dijkstras-algorithm.js
Labels: hacktoberfest-accepted

#405 Painter's Partition Problem in Java
  32. Java Programs/PainterPartitionProblem.java
Labels: hacktoberfest-accepted

#402 Create Subsets-II.cpp
  27. LeetCode Problems/Subsets-II.cpp
Labels: hacktoberfest-accepted

#401 Created Search in rotated and sorted array
  05. Searching/search_rotated_sorted_array.cpp
Labels: hacktoberfest-accepted

#465 Create Longest_Alternating_Subsequence.cpp
  20. Dynamic Programming/Longest_Alternating_Subsequence.cpp
Labels: hacktoberfest-accepted

#397 Create PathSum.cpp
  14. Tree/PathSum.cpp
Labels: hacktoberfest-accepted

#396 Create MissingNumber.cpp
  02. Bit Magic/MissingNumber.cpp
Labels: hacktoberfest-accepted

#407 Add 112. Path Sum in LeetCode Problems
  27. LeetCode Problems/PathSum.cpp
Labels: hacktoberfest-accepted
